export const BUSSES_REQUEST = "SF_MUNI_BUSSES_REQUEST";
export const BUSSES_SUCCESS = "SF_MUNI_BUSSES_SUCCESS";
export const BUSSES_FAILURE = "SF_BUSSES_FAILURE";

export const ADD_BUS_REQUEST = "SF_MUNI_ADD_BUS_REQUEST";
export const ADD_BUS_SUCCESS = "SF_MUNI_ADD_BUS_SUCCESS"
export const DELETE_BUS = "SF_MUNI_DELETE_BUS";
export const BUSSES_ON_HOVER = "SF_MUNI_BUSSES_ON_HOVER";
export const DELETE_ALL_ROUTES = "SF_MUNI_DELETE_ALL_ROUTES";
