export const ROUTES_INFO_REQUEST = "SF_MUNI_ROUTES_INFO_REQUEST";
export const ROUTES_INFO_SUCCESS = "SF_MUNI_ROUTES_INFO_SUCCESS";
export const ROUTES_INFO_FAILURE = "SF_MUNI_ROUTES_INFO_FAILURE";
export const ROUTES_LIST_REQUEST = "SF_MUNI_ROUTES_LIST_REQUEST";
export const ROUTES_LIST_SUCCESS = "SF_MUNI_ROUTES_LIST_SUCCESS";
export const ROUTES_LIST_FAILURE = "SF_MUNI_ROUTES_LIST_FAILURE";
