export const STREETS_INFO_REQUEST = "SF_MUNI_STREETS_INFO_REQUEST";
export const STREETS_INFO_SUCCESS = "SF_MUNI_STREETS_INFO_SUCCESS";
export const STREETS_INFO_FAILURE = "SF_MUNI_STREETS_INFO_FAILURE";
